from JUEGO import Juego
from random import seed

seed(1717)

"""
J = Juego()
J.IniciarJuego()
#J.Mostrar()
J.MoverEntreDestapadas(1,0,6)
#J.Mostrar()
J.MoverEntreDestapadas(0,0,1)
#J.Mostrar()
J.MoverEntreDestapadas(3,0,1)
#J.Mostrar()
J.MoverEntreDestapadas(1,0,3)
#J.Mostrar()
J.MoverEntreDestapadas(3,0,0)
#J.Mostrar()
J.MoverEntreDestapadas(0,1,3)
#J.Mostrar()
J.MoverEntreDestapadas(3,0,1)
#J.Mostrar()
J.MoverEntreDestapadas(3,0,1)
#J.Mostrar()

J.DestaparRobar()
#J.Mostrar()

J.SubirVistasColocadas(0)
#J.Mostrar()
J.SubirDestapadasColocadas(5, 0)
#J.Mostrar()
J.SubirDestapadasColocadas(2, 0)
#J.Mostrar()
J.MoverEntreDestapadas(2,0,1)
#J.Mostrar()
J.SubirDestapadasColocadas(2, 0)
#J.Mostrar()
J.SubirDestapadasColocadas(2, 1)
#J.Mostrar()
J.SubirDestapadasColocadas(6, 1)
#J.Mostrar()

for _ in range(8):J.DestaparRobar()
#J.Mostrar()
J.MoverVistasDestapadas(2)
#J.Mostrar()
for _ in range(9):J.DestaparRobar()
J.SubirVistasColocadas(2)
#J.Mostrar()
J.SubirDestapadasColocadas(5, 2)
#J.Mostrar()
for _ in range(5):J.DestaparRobar()
J.SubirVistasColocadas(3)
#J.Mostrar()
J.DestaparRobar()
#J.Mostrar()
#print("---")
J.DestaparRobar()
#J.Mostrar()
for _ in range(14):J.DestaparRobar()
J.SubirVistasColocadas(3)
#J.Mostrar()
J.SubirDestapadasColocadas(6, 3)
#J.Mostrar()
J.MoverEntreDestapadas(6, 0, 2)
#J.Mostrar()
for _ in range(6):J.DestaparRobar()
J.MoverVistasDestapadas(6)
#J.Mostrar()
J.DestaparRobar()
J.Mostrar()
for _ in range(9):J.DestaparRobar()
J.MoverVistasDestapadas(6)
J.Mostrar()
J.SubirDestapadasColocadas(6, 3)
"""
pass

"""
J = Juego()
J.IniciarJuego()
J.MoverEntreDestapadas(5,0,6)
J.Mostrar()
print("------------------------------------")
J.DestaparRobar()
J.Mostrar()
print("------------------------------------")
J.MoverVistasDestapadas(5)
J.Mostrar()
print("------------------------------------")
J.SubirDestapadasColocadas(5, 0)
J.Mostrar()
print("------------------------------------")
J.MoverColocadasDestapadas(0, 5)
J.Mostrar()
"""